### ISSUE TITLE
must_local doesn't work for users with no write access to $dir

### ISSUE THREAD

**Issue by anakaiti** [payfazz/docker-sh#1]
```
****: Pulling from ****/****
Digest: sha256:****
Status: Image is up to date for ****/****:****
Recreating container ...
/usr/bin/docker.sh: line 172: /container_state/****/recharge/bc280333ae05d8cf: Permission denied
rm: cannot remove '/container_state/****/recharge/bc280333ae05d8cf': Is a directory
docker daemon is not running on local machine
```

**Comment by win-t** [comment]
`must_local` is implemented by creating a random file with random content in the host, and mount it on a container, the docker is local if the file in container contains the same value with file in the host,

that error is because of docker.sh invoked by a user that doesn't have permission to create a file in the directory

**Comment by win-t** [comment]
improved by https://github.com/payfazz/docker-sh/commit/96593517a8632d9c6065f8d64369651eb93d097c
